Fix mov to CR/DR compilation error
In Intel SDM 2B chapter 4.3 "MOV - Move to/from Control Registers" and
"MOV - Move to/from Debug Registers" when it's 64-bit mode it's required
to use r64 to/from debug/control registers. And immediate will be treated
as 32 bit. The test hsi_virtual_spec and exception_gp_b6 are only built
for 64 bit, so rewrite to 64 bit version and fix the error.

Previous compilation error:
```
x86/hsi_vmx_exe_contrl0.c: Assembler messages:
x86/hsi_vmx_exe_contrl0.c:95: Error: unsupported instruction `mov'

x86/exception_gp_b6.c:1398: Error: unsupported instruction `mov'
x86/exception_gp_b6.c:1390: Error: unsupported instruction `mov'
```

Signed-off-by: Xin Zhang <xin.x.zhang@intel.com>