Fix build error of multiple definition of 'xsave_st'
This error causes many tests' build failure.

/usr/bin/ld: lib/libcflat.a(register_op.o):/acrn-unit-test/guest/lib/x86/xsave.h:59:
multiple definition of `xsave_st';
lib/libcflat.a(misc.o)://acrn-unit-test/guest/lib/x86/xsave.h:59: first defined here
collect2: error: ld returned 1 exit status